--------------------------------------------------------
--  DDL for Table CURSO
--------------------------------------------------------

  CREATE TABLE "ROOT2"."CURSO" 
   (	"ID_CURSO" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_USUARIOS" ;
--------------------------------------------------------
--  DDL for Table DOCENTE
--------------------------------------------------------

  CREATE TABLE "ROOT2"."DOCENTE" 
   (	"ID_DOCENTE" NUMBER, 
	"ASIGNATURA" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_USUARIOS" ;
--------------------------------------------------------
--  DDL for Table DOCENTE_GRUPO
--------------------------------------------------------

  CREATE TABLE "ROOT2"."DOCENTE_GRUPO" 
   (	"ID_DOCENTE" NUMBER, 
	"ID_GRUPO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_USUARIOS" ;
--------------------------------------------------------
--  DDL for Table ESTADISTICAS_ESTUDIANTE
--------------------------------------------------------

  CREATE TABLE "ROOT2"."ESTADISTICAS_ESTUDIANTE" 
   (	"ID_ESTUDIANTE" NUMBER(*,0), 
	"TOTAL_EXAMENES_PRESENTADOS" NUMBER(*,0), 
	"PREGUNTAS_CORRECTAS" NUMBER(*,0), 
	"PREGUNTAS_INCORRECTAS" NUMBER(*,0), 
	"PROMEDIO_NOTA" NUMBER(5,2), 
	"MAX_NOTA" NUMBER(5,2), 
	"MIN_NOTA" NUMBER(5,2)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TBS_ESTADISTICAS" ;
--------------------------------------------------------
--  DDL for Table ESTADISTICAS_EXAMEN
--------------------------------------------------------

  CREATE TABLE "ROOT2"."ESTADISTICAS_EXAMEN" 
   (	"ID_ESTADISTICA" NUMBER, 
	"ID_EXAMEN" NUMBER, 
	"TOTAL_PRESENTADOS" NUMBER, 
	"PROMEDIO_NOTA" NUMBER, 
	"MAX_NOTA" NUMBER, 
	"MIN_NOTA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ESTADISTICAS" ;
--------------------------------------------------------
--  DDL for Table ESTADISTICAS_GRUPO
--------------------------------------------------------

  CREATE TABLE "ROOT2"."ESTADISTICAS_GRUPO" 
   (	"ID_GRUPO" NUMBER(*,0), 
	"TOTAL_EXAMENES_PRESENTADOS" NUMBER(*,0), 
	"PROMEDIO_GENERAL" NUMBER(5,2), 
	"MAX_NOTA" NUMBER(5,2), 
	"MIN_NOTA" NUMBER(5,2)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TBS_ESTADISTICAS" ;
--------------------------------------------------------
--  DDL for Table ESTADISTICAS_PREGUNTA
--------------------------------------------------------

  CREATE TABLE "ROOT2"."ESTADISTICAS_PREGUNTA" 
   (	"ID_PREGUNTA" NUMBER, 
	"PORCENTAJE_CORRECTAS" NUMBER, 
	"TOTAL_RESPUESTAS" NUMBER, 
	"CORRECTAS" NUMBER, 
	"INCORRECTAS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ESTADISTICAS" ;
--------------------------------------------------------
--  DDL for Table ESTADISTICAS_TEMA
--------------------------------------------------------

  CREATE TABLE "ROOT2"."ESTADISTICAS_TEMA" 
   (	"ID_TEMA" NUMBER(*,0), 
	"TOTAL_PREGUNTAS" NUMBER(*,0), 
	"TOTAL_CORRECTAS" NUMBER(*,0), 
	"TOTAL_INCORRECTAS" NUMBER(*,0), 
	"PROMEDIO_NOTA" NUMBER(5,2), 
	"MAX_NOTA" NUMBER(5,2), 
	"MIN_NOTA" NUMBER(5,2)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TBS_ESTADISTICAS" ;
--------------------------------------------------------
--  DDL for Table ESTUDIANTE
--------------------------------------------------------

  CREATE TABLE "ROOT2"."ESTUDIANTE" 
   (	"ID_ESTUDIANTE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_USUARIOS" ;
--------------------------------------------------------
--  DDL for Table ESTUDIANTE_GRUPO
--------------------------------------------------------

  CREATE TABLE "ROOT2"."ESTUDIANTE_GRUPO" 
   (	"ID_ESTUDIANTE" NUMBER, 
	"ID_GRUPO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_USUARIOS" ;
--------------------------------------------------------
--  DDL for Table EXAMEN
--------------------------------------------------------

  CREATE TABLE "ROOT2"."EXAMEN" 
   (	"ID_EXAMEN" NUMBER DEFAULT "ROOT2"."SEQ_EXAMEN"."NEXTVAL", 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(255 BYTE), 
	"FECHA_INICIO" DATE, 
	"FECHA_FIN" DATE, 
	"TIEMPO_LIMITE" NUMBER, 
	"ID_DOCENTE" NUMBER, 
	"NUMERO_PREGUNTAS" NUMBER, 
	"MODO_SELECCION" VARCHAR2(20 BYTE), 
	"TIEMPO_POR_PREGUNTA" NUMBER, 
	"ID_TEMA" NUMBER, 
	"ES_SIN_TIEMPO" NUMBER(1,0) DEFAULT 0, 
	"NUM_PREGUNTAS_ALEATORIAS" NUMBER, 
	"PESO_CURSO" NUMBER(5,2), 
	"NOTA_MINIMA_APROBACION" NUMBER(2,1) DEFAULT 3.0, 
	"ID_GRUPO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_EXAMENES" ;
--------------------------------------------------------
--  DDL for Table EXAMEN_PREGUNTA
--------------------------------------------------------

  CREATE TABLE "ROOT2"."EXAMEN_PREGUNTA" 
   (	"ID_EXAMEN" NUMBER, 
	"ID_PREGUNTA" NUMBER, 
	"VALOR_NOTA" NUMBER(3,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_EXAMENES" ;
--------------------------------------------------------
--  DDL for Table GRUPO
--------------------------------------------------------

  CREATE TABLE "ROOT2"."GRUPO" 
   (	"ID_GRUPO" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"ID_CURSO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_USUARIOS" ;
--------------------------------------------------------
--  DDL for Table HORARIO
--------------------------------------------------------

  CREATE TABLE "ROOT2"."HORARIO" 
   (	"ID_HORARIO" NUMBER, 
	"ID_GRUPO" NUMBER, 
	"DIA_SEMANA" VARCHAR2(15 BYTE), 
	"HORA_INICIO" DATE, 
	"HORA_FIN" DATE, 
	"LUGAR" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TBS_PLANESTUDIO" ;
--------------------------------------------------------
--  DDL for Table PLAN_ESTUDIO
--------------------------------------------------------

  CREATE TABLE "ROOT2"."PLAN_ESTUDIO" 
   (	"ID_PLAN" NUMBER, 
	"ID_CURSO" NUMBER, 
	"VERSION_PLAN" VARCHAR2(10 BYTE), 
	"DESCRIPCION" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PLANESTUDIO" ;
--------------------------------------------------------
--  DDL for Table PREGUNTA
--------------------------------------------------------

  CREATE TABLE "ROOT2"."PREGUNTA" 
   (	"ID_PREGUNTA" NUMBER DEFAULT "ROOT2"."SEQ_PREGUNTA"."NEXTVAL", 
	"TEXTO" CLOB, 
	"TIPO" VARCHAR2(50 BYTE), 
	"ID_TEMA" NUMBER, 
	"ES_PUBLICA" CHAR(1 BYTE) DEFAULT 'N', 
	"ID_PREGUNTA_PADRE" NUMBER, 
	"VALOR_NOTA" NUMBER(3,2), 
	"ID_DOCENTE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_EXAMENES" 
 LOB ("TEXTO") STORE AS SECUREFILE (
  TABLESPACE "TBS_LOB" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table PRESENTACION_EXAMEN
--------------------------------------------------------

  CREATE TABLE "ROOT2"."PRESENTACION_EXAMEN" 
   (	"ID_PRESENTACION" NUMBER, 
	"ID_EXAMEN" NUMBER, 
	"ID_ESTUDIANTE" NUMBER, 
	"FECHA_PRESENTACION" DATE, 
	"CALIFICACION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PRESENTACION" ;
--------------------------------------------------------
--  DDL for Table RESPUESTA
--------------------------------------------------------

  CREATE TABLE "ROOT2"."RESPUESTA" 
   (	"ID_RESPUESTA" NUMBER, 
	"ID_PREGUNTA" NUMBER, 
	"TEXTO" VARCHAR2(255 BYTE), 
	"ES_CORRECTA" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_EXAMENES" ;
--------------------------------------------------------
--  DDL for Table RESPUESTA_ESTUDIANTE
--------------------------------------------------------

  CREATE TABLE "ROOT2"."RESPUESTA_ESTUDIANTE" 
   (	"ID_RESPUESTA_ESTUDIANTE" NUMBER, 
	"ID_PRESENTACION" NUMBER, 
	"ID_PREGUNTA" NUMBER, 
	"ID_RESPUESTA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PRESENTACION" ;
--------------------------------------------------------
--  DDL for Table TEMA
--------------------------------------------------------

  CREATE TABLE "ROOT2"."TEMA" 
   (	"ID_TEMA" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"ID_UNIDAD" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PLANESTUDIO" ;
--------------------------------------------------------
--  DDL for Table UNIDAD
--------------------------------------------------------

  CREATE TABLE "ROOT2"."UNIDAD" 
   (	"ID_UNIDAD" NUMBER, 
	"ID_PLAN" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(200 BYTE), 
	"ORDEN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PLANESTUDIO" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "ROOT2"."USUARIO" 
   (	"ID_USUARIO" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"CORREO" VARCHAR2(100 BYTE), 
	"CONTRASENA" VARCHAR2(100 BYTE), 
	"TIPO_USUARIO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_USUARIOS" ;
--------------------------------------------------------
--  DDL for View VISTA_ESTADISTICAS_ESTUDIANTE
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ROOT2"."VISTA_ESTADISTICAS_ESTUDIANTE" ("ID_ESTUDIANTE", "NOMBRE", "TOTAL_EXAMENES_PRESENTADOS", "TOTAL_RESPUESTAS", "PREGUNTAS_CORRECTAS", "PREGUNTAS_INCORRECTAS", "PROMEDIO_NOTA", "MAX_NOTA", "MIN_NOTA") AS 
  SELECT 
    e.id_estudiante AS id_estudiante,
    u.nombre AS nombre,
    COUNT(DISTINCT pres.id_presentacion) AS total_examenes_presentados,
    COUNT(res_est.id_respuesta_estudiante) AS total_respuestas,
    SUM(CASE WHEN r.es_correcta = 1 THEN 1 ELSE 0 END) AS preguntas_correctas,
    SUM(CASE WHEN r.es_correcta = 0 THEN 1 ELSE 0 END) AS preguntas_incorrectas,
    ROUND(AVG(pres.calificacion), 2) AS promedio_nota,
    MAX(pres.calificacion) AS max_nota,
    MIN(pres.calificacion) AS min_nota
FROM 
    ESTUDIANTE e
JOIN 
    USUARIO u ON u.id_usuario = e.id_estudiante
JOIN 
    PRESENTACION_EXAMEN pres ON pres.id_estudiante = e.id_estudiante
LEFT JOIN 
    RESPUESTA_ESTUDIANTE res_est ON res_est.id_presentacion = pres.id_presentacion
LEFT JOIN 
    RESPUESTA r ON r.id_respuesta = res_est.id_respuesta
GROUP BY 
    e.id_estudiante, u.nombre
;
--------------------------------------------------------
--  DDL for View VISTA_ESTADISTICAS_EXAMEN
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ROOT2"."VISTA_ESTADISTICAS_EXAMEN" ("ID_EXAMEN", "NOMBRE", "TOTAL_PRESENTACIONES", "PROMEDIO_NOTA", "MAX_NOTA", "MIN_NOTA") AS 
  SELECT 
    e.id_examen,
    e.nombre,
    COUNT(pres.id_presentacion) AS total_presentaciones,
    ROUND(AVG(pres.calificacion), 2) AS promedio_nota,
    MAX(pres.calificacion) AS max_nota,
    MIN(pres.calificacion) AS min_nota
FROM 
    EXAMEN e
LEFT JOIN 
    PRESENTACION_EXAMEN pres ON pres.id_examen = e.id_examen
GROUP BY 
    e.id_examen, e.nombre
;
--------------------------------------------------------
--  DDL for View VISTA_ESTADISTICAS_GRUPO
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ROOT2"."VISTA_ESTADISTICAS_GRUPO" ("ID_GRUPO", "GRUPO", "TOTAL_EXAMENES_PRESENTADOS", "PROMEDIO_GENERAL", "MAX_NOTA", "MIN_NOTA") AS 
  SELECT 
    g.id_grupo,
    g.nombre AS grupo,
    COUNT(DISTINCT pres.id_presentacion) AS total_examenes_presentados,
    ROUND(AVG(pres.calificacion), 2) AS promedio_general,
    MAX(pres.calificacion) AS max_nota,
    MIN(pres.calificacion) AS min_nota
FROM 
    GRUPO g
JOIN 
    ESTUDIANTE_GRUPO eg ON eg.id_grupo = g.id_grupo
JOIN 
    PRESENTACION_EXAMEN pres ON pres.id_estudiante = eg.id_estudiante
GROUP BY 
    g.id_grupo, g.nombre
;
--------------------------------------------------------
--  DDL for View VISTA_ESTADISTICAS_PREGUNTA
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ROOT2"."VISTA_ESTADISTICAS_PREGUNTA" ("ID_PREGUNTA", "PREGUNTA", "TEMA", "TOTAL_RESPUESTAS", "TOTAL_CORRECTAS", "TOTAL_INCORRECTAS", "PORCENTAJE_ACIERTOS") AS 
  SELECT 
    p.id_pregunta,
    DBMS_LOB.SUBSTR(p.texto, 4000, 1) AS pregunta,
    t.nombre AS tema,
    COUNT(re.id_respuesta_estudiante) AS total_respuestas,
    SUM(CASE WHEN r.es_correcta = 1 THEN 1 ELSE 0 END) AS total_correctas,
    SUM(CASE WHEN r.es_correcta = 0 THEN 1 ELSE 0 END) AS total_incorrectas,
    ROUND(
        CASE 
            WHEN COUNT(re.id_respuesta_estudiante) = 0 THEN 0
            ELSE 
                (SUM(CASE WHEN r.es_correcta = 1 THEN 1 ELSE 0 END) * 100.0) / COUNT(re.id_respuesta_estudiante)
        END
    , 2) AS porcentaje_aciertos
FROM 
    PREGUNTA p
JOIN 
    TEMA t ON t.id_tema = p.id_tema
LEFT JOIN 
    RESPUESTA_ESTUDIANTE re ON re.id_pregunta = p.id_pregunta
LEFT JOIN 
    RESPUESTA r ON r.id_respuesta = re.id_respuesta
GROUP BY 
    p.id_pregunta, DBMS_LOB.SUBSTR(p.texto, 4000, 1), t.nombre
;
--------------------------------------------------------
--  DDL for View VISTA_ESTADISTICAS_TEMA
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ROOT2"."VISTA_ESTADISTICAS_TEMA" ("ID_TEMA", "TEMA", "TOTAL_RESPUESTAS", "TOTAL_CORRECTAS", "TOTAL_INCORRECTAS", "PROMEDIO_NOTA", "MAX_NOTA", "MIN_NOTA") AS 
  SELECT 
    t.id_tema,
    t.nombre AS tema,
    COUNT(re.id_respuesta_estudiante) AS total_respuestas,
    SUM(CASE WHEN pe.es_correcta = 1 THEN 1 ELSE 0 END) AS total_correctas,
    SUM(CASE WHEN NOT pe.es_correcta = 0 THEN 1 ELSE 0 END) AS total_incorrectas,
    ROUND(AVG(pres.calificacion), 2) AS promedio_nota,
    MAX(pres.calificacion) AS max_nota,
    MIN(pres.calificacion) AS min_nota
FROM 
    TEMA t
JOIN 
    PREGUNTA p ON p.id_tema = t.id_tema
JOIN 
    RESPUESTA pe ON pe.id_pregunta = p.id_pregunta
JOIN 
    RESPUESTA_ESTUDIANTE re ON re.id_respuesta = pe.id_respuesta
JOIN
    PRESENTACION_EXAMEN pres ON pres.id_presentacion = re.id_presentacion
GROUP BY 
    t.id_tema, t.nombre
;
--------------------------------------------------------
--  DDL for Index PK_HORARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT2"."PK_HORARIO" ON "ROOT2"."HORARIO" ("ID_HORARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_INDICES" ;
--------------------------------------------------------
--  DDL for Index PK_PRESENTACION_EXAMEN
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT2"."PK_PRESENTACION_EXAMEN" ON "ROOT2"."PRESENTACION_EXAMEN" ("ID_PRESENTACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES" ;
--------------------------------------------------------
--  DDL for Index PK_PREGUNTA
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT2"."PK_PREGUNTA" ON "ROOT2"."PREGUNTA" ("ID_PREGUNTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES" ;
--------------------------------------------------------
--  DDL for Index PK_ESTADISTICAS_TEMA
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT2"."PK_ESTADISTICAS_TEMA" ON "ROOT2"."ESTADISTICAS_TEMA" ("ID_TEMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_INDICES" ;
--------------------------------------------------------
--  DDL for Index PK_ESTADISTICAS_ESTUDIANTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT2"."PK_ESTADISTICAS_ESTUDIANTE" ON "ROOT2"."ESTADISTICAS_ESTUDIANTE" ("ID_ESTUDIANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_INDICES" ;
--------------------------------------------------------
--  DDL for Index PK_GRUPO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT2"."PK_GRUPO" ON "ROOT2"."GRUPO" ("ID_GRUPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES" ;
--------------------------------------------------------
--  DDL for Index PK_EXAMEN_PREGUNTA
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT2"."PK_EXAMEN_PREGUNTA" ON "ROOT2"."EXAMEN_PREGUNTA" ("ID_EXAMEN", "ID_PREGUNTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES" ;
--------------------------------------------------------
--  DDL for Index PK_CURSO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT2"."PK_CURSO" ON "ROOT2"."CURSO" ("ID_CURSO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES" ;
--------------------------------------------------------
--  DDL for Index PK_DOCENTE_GRUPO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT2"."PK_DOCENTE_GRUPO" ON "ROOT2"."DOCENTE_GRUPO" ("ID_DOCENTE", "ID_GRUPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES" ;
--------------------------------------------------------
--  DDL for Index PK_ESTUDIANTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT2"."PK_ESTUDIANTE" ON "ROOT2"."ESTUDIANTE" ("ID_ESTUDIANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES" ;
--------------------------------------------------------
--  DDL for Index PK_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT2"."PK_USUARIO" ON "ROOT2"."USUARIO" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES" ;
--------------------------------------------------------
--  DDL for Index PK_ESTADISTICAS_PREGUNTA
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT2"."PK_ESTADISTICAS_PREGUNTA" ON "ROOT2"."ESTADISTICAS_PREGUNTA" ("ID_PREGUNTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES" ;
--------------------------------------------------------
--  DDL for Index PK_EXAMEN
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT2"."PK_EXAMEN" ON "ROOT2"."EXAMEN" ("ID_EXAMEN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES" ;
--------------------------------------------------------
--  DDL for Index PK_ESTADISTICAS_EXAMEN
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT2"."PK_ESTADISTICAS_EXAMEN" ON "ROOT2"."ESTADISTICAS_EXAMEN" ("ID_ESTADISTICA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES" ;
--------------------------------------------------------
--  DDL for Index PK_DOCENTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT2"."PK_DOCENTE" ON "ROOT2"."DOCENTE" ("ID_DOCENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES" ;
--------------------------------------------------------
--  DDL for Index PK_RESPUESTA
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT2"."PK_RESPUESTA" ON "ROOT2"."RESPUESTA" ("ID_RESPUESTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES" ;
--------------------------------------------------------
--  DDL for Index PK_RESPUESTA_ESTUDIANTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT2"."PK_RESPUESTA_ESTUDIANTE" ON "ROOT2"."RESPUESTA_ESTUDIANTE" ("ID_RESPUESTA_ESTUDIANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES" ;
--------------------------------------------------------
--  DDL for Index PK_TEMA
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT2"."PK_TEMA" ON "ROOT2"."TEMA" ("ID_TEMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES" ;
--------------------------------------------------------
--  DDL for Index PK_ESTADISTICAS_GRUPO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT2"."PK_ESTADISTICAS_GRUPO" ON "ROOT2"."ESTADISTICAS_GRUPO" ("ID_GRUPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_INDICES" ;
--------------------------------------------------------
--  DDL for Index PK_PLAN_ESTUDIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT2"."PK_PLAN_ESTUDIO" ON "ROOT2"."PLAN_ESTUDIO" ("ID_PLAN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES" ;
--------------------------------------------------------
--  DDL for Index PK_UNIDAD
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT2"."PK_UNIDAD" ON "ROOT2"."UNIDAD" ("ID_UNIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES" ;

--------------------------------------------------------
--  Constraints for Table ESTADISTICAS_ESTUDIANTE
--------------------------------------------------------

  ALTER TABLE "ROOT2"."ESTADISTICAS_ESTUDIANTE" ADD PRIMARY KEY ("ID_ESTUDIANTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_INDICES"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DOCENTE
--------------------------------------------------------

  ALTER TABLE "ROOT2"."DOCENTE" ADD PRIMARY KEY ("ID_DOCENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CURSO
--------------------------------------------------------

  ALTER TABLE "ROOT2"."CURSO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ROOT2"."CURSO" ADD PRIMARY KEY ("ID_CURSO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TEMA
--------------------------------------------------------

  ALTER TABLE "ROOT2"."TEMA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ROOT2"."TEMA" ADD PRIMARY KEY ("ID_TEMA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES"  ENABLE;
  ALTER TABLE "ROOT2"."TEMA" MODIFY ("ID_UNIDAD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HORARIO
--------------------------------------------------------

  ALTER TABLE "ROOT2"."HORARIO" MODIFY ("ID_GRUPO" NOT NULL ENABLE);
  ALTER TABLE "ROOT2"."HORARIO" ADD PRIMARY KEY ("ID_HORARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_INDICES"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PLAN_ESTUDIO
--------------------------------------------------------

  ALTER TABLE "ROOT2"."PLAN_ESTUDIO" MODIFY ("ID_CURSO" NOT NULL ENABLE);
  ALTER TABLE "ROOT2"."PLAN_ESTUDIO" ADD PRIMARY KEY ("ID_PLAN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRESENTACION_EXAMEN
--------------------------------------------------------

  ALTER TABLE "ROOT2"."PRESENTACION_EXAMEN" ADD PRIMARY KEY ("ID_PRESENTACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ESTADISTICAS_TEMA
--------------------------------------------------------

  ALTER TABLE "ROOT2"."ESTADISTICAS_TEMA" ADD PRIMARY KEY ("ID_TEMA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_INDICES"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EXAMEN
--------------------------------------------------------

  ALTER TABLE "ROOT2"."EXAMEN" ADD PRIMARY KEY ("ID_EXAMEN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES"  ENABLE;
  ALTER TABLE "ROOT2"."EXAMEN" ADD CHECK (modo_seleccion IN ('Manual', 'Aleatorio')) ENABLE;
  ALTER TABLE "ROOT2"."EXAMEN" ADD CHECK (modo_seleccion IN ('Manual', 'Aleatorio')) ENABLE;
  ALTER TABLE "ROOT2"."EXAMEN" MODIFY ("ID_TEMA" NOT NULL ENABLE);
  ALTER TABLE "ROOT2"."EXAMEN" ADD CHECK (modo_seleccion IN ('Manual', 'Aleatorio')) ENABLE;
  ALTER TABLE "ROOT2"."EXAMEN" ADD CHECK (modo_seleccion IN ('Manual', 'Aleatorio')) ENABLE;
  ALTER TABLE "ROOT2"."EXAMEN" ADD CHECK (modo_seleccion IN ('Manual', 'Aleatorio')) ENABLE;
  ALTER TABLE "ROOT2"."EXAMEN" ADD CHECK (modo_seleccion IN ('Manual', 'Aleatorio')) ENABLE;
  ALTER TABLE "ROOT2"."EXAMEN" ADD CHECK (modo_seleccion IN ('Manual', 'Aleatorio')) ENABLE;
  ALTER TABLE "ROOT2"."EXAMEN" ADD CHECK (modo_seleccion IN ('Manual', 'Aleatorio')) ENABLE;
--------------------------------------------------------
--  Constraints for Table ESTADISTICAS_PREGUNTA
--------------------------------------------------------

  ALTER TABLE "ROOT2"."ESTADISTICAS_PREGUNTA" ADD PRIMARY KEY ("ID_PREGUNTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ESTUDIANTE_GRUPO
--------------------------------------------------------

  ALTER TABLE "ROOT2"."ESTUDIANTE_GRUPO" MODIFY ("ID_ESTUDIANTE" NOT NULL ENABLE);
  ALTER TABLE "ROOT2"."ESTUDIANTE_GRUPO" MODIFY ("ID_GRUPO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DOCENTE_GRUPO
--------------------------------------------------------

  ALTER TABLE "ROOT2"."DOCENTE_GRUPO" ADD PRIMARY KEY ("ID_DOCENTE", "ID_GRUPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ESTADISTICAS_GRUPO
--------------------------------------------------------

  ALTER TABLE "ROOT2"."ESTADISTICAS_GRUPO" ADD PRIMARY KEY ("ID_GRUPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_INDICES"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PREGUNTA
--------------------------------------------------------

  ALTER TABLE "ROOT2"."PREGUNTA" MODIFY ("ID_TEMA" NOT NULL ENABLE);
  ALTER TABLE "ROOT2"."PREGUNTA" MODIFY ("ID_PREGUNTA" NOT NULL ENABLE);
  ALTER TABLE "ROOT2"."PREGUNTA" ADD PRIMARY KEY ("ID_PREGUNTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES"  ENABLE;
  ALTER TABLE "ROOT2"."PREGUNTA" ADD CHECK (es_publica IN ('S', 'N')) ENABLE;
  ALTER TABLE "ROOT2"."PREGUNTA" ADD CHECK (es_publica IN ('S', 'N')) ENABLE;
  ALTER TABLE "ROOT2"."PREGUNTA" ADD CHECK (es_publica IN ('S', 'N')) ENABLE;
  ALTER TABLE "ROOT2"."PREGUNTA" ADD CHECK (es_publica IN ('S', 'N')) ENABLE;
--------------------------------------------------------
--  Constraints for Table RESPUESTA
--------------------------------------------------------

  ALTER TABLE "ROOT2"."RESPUESTA" ADD PRIMARY KEY ("ID_RESPUESTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EXAMEN_PREGUNTA
--------------------------------------------------------

  ALTER TABLE "ROOT2"."EXAMEN_PREGUNTA" ADD CONSTRAINT "PK_EXAMEN_PREGUNTA" PRIMARY KEY ("ID_EXAMEN", "ID_PREGUNTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESPUESTA_ESTUDIANTE
--------------------------------------------------------

  ALTER TABLE "ROOT2"."RESPUESTA_ESTUDIANTE" ADD PRIMARY KEY ("ID_RESPUESTA_ESTUDIANTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "ROOT2"."USUARIO" ADD PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GRUPO
--------------------------------------------------------

  ALTER TABLE "ROOT2"."GRUPO" ADD PRIMARY KEY ("ID_GRUPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES"  ENABLE;
  ALTER TABLE "ROOT2"."GRUPO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ROOT2"."GRUPO" MODIFY ("ID_CURSO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESTUDIANTE
--------------------------------------------------------

  ALTER TABLE "ROOT2"."ESTUDIANTE" ADD PRIMARY KEY ("ID_ESTUDIANTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ESTADISTICAS_EXAMEN
--------------------------------------------------------

  ALTER TABLE "ROOT2"."ESTADISTICAS_EXAMEN" ADD PRIMARY KEY ("ID_ESTADISTICA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES"  ENABLE;
--------------------------------------------------------
--  Constraints for Table UNIDAD
--------------------------------------------------------

  ALTER TABLE "ROOT2"."UNIDAD" MODIFY ("ID_PLAN" NOT NULL ENABLE);
  ALTER TABLE "ROOT2"."UNIDAD" ADD PRIMARY KEY ("ID_UNIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_INDICES"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DOCENTE
--------------------------------------------------------

  ALTER TABLE "ROOT2"."DOCENTE" ADD CONSTRAINT "FK_DOCENTE_USUARIO" FOREIGN KEY ("ID_DOCENTE")
	  REFERENCES "ROOT2"."USUARIO" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DOCENTE_GRUPO
--------------------------------------------------------

  ALTER TABLE "ROOT2"."DOCENTE_GRUPO" ADD CONSTRAINT "FK_DOCENTEGRUPO_DOCENTE" FOREIGN KEY ("ID_DOCENTE")
	  REFERENCES "ROOT2"."DOCENTE" ("ID_DOCENTE") ENABLE;
  ALTER TABLE "ROOT2"."DOCENTE_GRUPO" ADD CONSTRAINT "FK_DOCENTEGRUPO_GRUPO" FOREIGN KEY ("ID_GRUPO")
	  REFERENCES "ROOT2"."GRUPO" ("ID_GRUPO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESTADISTICAS_ESTUDIANTE
--------------------------------------------------------

  ALTER TABLE "ROOT2"."ESTADISTICAS_ESTUDIANTE" ADD FOREIGN KEY ("ID_ESTUDIANTE")
	  REFERENCES "ROOT2"."ESTUDIANTE" ("ID_ESTUDIANTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESTADISTICAS_EXAMEN
--------------------------------------------------------

  ALTER TABLE "ROOT2"."ESTADISTICAS_EXAMEN" ADD FOREIGN KEY ("ID_EXAMEN")
	  REFERENCES "ROOT2"."EXAMEN" ("ID_EXAMEN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESTADISTICAS_GRUPO
--------------------------------------------------------

  ALTER TABLE "ROOT2"."ESTADISTICAS_GRUPO" ADD FOREIGN KEY ("ID_GRUPO")
	  REFERENCES "ROOT2"."GRUPO" ("ID_GRUPO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESTADISTICAS_PREGUNTA
--------------------------------------------------------

  ALTER TABLE "ROOT2"."ESTADISTICAS_PREGUNTA" ADD FOREIGN KEY ("ID_PREGUNTA")
	  REFERENCES "ROOT2"."PREGUNTA" ("ID_PREGUNTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESTADISTICAS_TEMA
--------------------------------------------------------

  ALTER TABLE "ROOT2"."ESTADISTICAS_TEMA" ADD FOREIGN KEY ("ID_TEMA")
	  REFERENCES "ROOT2"."TEMA" ("ID_TEMA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESTUDIANTE
--------------------------------------------------------

  ALTER TABLE "ROOT2"."ESTUDIANTE" ADD CONSTRAINT "FK_ESTUDIANTE_USUARIO" FOREIGN KEY ("ID_ESTUDIANTE")
	  REFERENCES "ROOT2"."USUARIO" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESTUDIANTE_GRUPO
--------------------------------------------------------

  ALTER TABLE "ROOT2"."ESTUDIANTE_GRUPO" ADD CONSTRAINT "ESTUDIANTE_GRUPO_FK" FOREIGN KEY ("ID_ESTUDIANTE")
	  REFERENCES "ROOT2"."ESTUDIANTE" ("ID_ESTUDIANTE") ENABLE;
  ALTER TABLE "ROOT2"."ESTUDIANTE_GRUPO" ADD CONSTRAINT "ESTUDIANTE_GRUPO_FK2" FOREIGN KEY ("ID_GRUPO")
	  REFERENCES "ROOT2"."GRUPO" ("ID_GRUPO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EXAMEN
--------------------------------------------------------

  ALTER TABLE "ROOT2"."EXAMEN" ADD FOREIGN KEY ("ID_DOCENTE")
	  REFERENCES "ROOT2"."USUARIO" ("ID_USUARIO") ENABLE;
  ALTER TABLE "ROOT2"."EXAMEN" ADD CONSTRAINT "FK_EXAMEN_TEMA" FOREIGN KEY ("ID_TEMA")
	  REFERENCES "ROOT2"."TEMA" ("ID_TEMA") ENABLE;
  ALTER TABLE "ROOT2"."EXAMEN" ADD CONSTRAINT "FK_EXAMEN_DOCENTE" FOREIGN KEY ("ID_DOCENTE")
	  REFERENCES "ROOT2"."DOCENTE" ("ID_DOCENTE") ENABLE;
  ALTER TABLE "ROOT2"."EXAMEN" ADD CONSTRAINT "FK_EXAMEN_GRUPO" FOREIGN KEY ("ID_GRUPO")
	  REFERENCES "ROOT2"."GRUPO" ("ID_GRUPO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EXAMEN_PREGUNTA
--------------------------------------------------------

  ALTER TABLE "ROOT2"."EXAMEN_PREGUNTA" ADD FOREIGN KEY ("ID_EXAMEN")
	  REFERENCES "ROOT2"."EXAMEN" ("ID_EXAMEN") ENABLE;
  ALTER TABLE "ROOT2"."EXAMEN_PREGUNTA" ADD FOREIGN KEY ("ID_PREGUNTA")
	  REFERENCES "ROOT2"."PREGUNTA" ("ID_PREGUNTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GRUPO
--------------------------------------------------------

  ALTER TABLE "ROOT2"."GRUPO" ADD FOREIGN KEY ("ID_CURSO")
	  REFERENCES "ROOT2"."CURSO" ("ID_CURSO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HORARIO
--------------------------------------------------------

  ALTER TABLE "ROOT2"."HORARIO" ADD FOREIGN KEY ("ID_GRUPO")
	  REFERENCES "ROOT2"."GRUPO" ("ID_GRUPO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLAN_ESTUDIO
--------------------------------------------------------

  ALTER TABLE "ROOT2"."PLAN_ESTUDIO" ADD FOREIGN KEY ("ID_CURSO")
	  REFERENCES "ROOT2"."CURSO" ("ID_CURSO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PREGUNTA
--------------------------------------------------------

  ALTER TABLE "ROOT2"."PREGUNTA" ADD FOREIGN KEY ("ID_PREGUNTA_PADRE")
	  REFERENCES "ROOT2"."PREGUNTA" ("ID_PREGUNTA") ENABLE;
  ALTER TABLE "ROOT2"."PREGUNTA" ADD CONSTRAINT "FK_PREGUNTA_TEMA" FOREIGN KEY ("ID_TEMA")
	  REFERENCES "ROOT2"."TEMA" ("ID_TEMA") ENABLE;
  ALTER TABLE "ROOT2"."PREGUNTA" ADD CONSTRAINT "FK_PREGUNTAS_DOCENTE" FOREIGN KEY ("ID_DOCENTE")
	  REFERENCES "ROOT2"."DOCENTE" ("ID_DOCENTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRESENTACION_EXAMEN
--------------------------------------------------------

  ALTER TABLE "ROOT2"."PRESENTACION_EXAMEN" ADD FOREIGN KEY ("ID_EXAMEN")
	  REFERENCES "ROOT2"."EXAMEN" ("ID_EXAMEN") ENABLE;
  ALTER TABLE "ROOT2"."PRESENTACION_EXAMEN" ADD FOREIGN KEY ("ID_ESTUDIANTE")
	  REFERENCES "ROOT2"."USUARIO" ("ID_USUARIO") ENABLE;
  ALTER TABLE "ROOT2"."PRESENTACION_EXAMEN" ADD CONSTRAINT "FK_PRESENTACION_ESTUDIANTE" FOREIGN KEY ("ID_ESTUDIANTE")
	  REFERENCES "ROOT2"."ESTUDIANTE" ("ID_ESTUDIANTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESPUESTA
--------------------------------------------------------

  ALTER TABLE "ROOT2"."RESPUESTA" ADD FOREIGN KEY ("ID_PREGUNTA")
	  REFERENCES "ROOT2"."PREGUNTA" ("ID_PREGUNTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESPUESTA_ESTUDIANTE
--------------------------------------------------------

  ALTER TABLE "ROOT2"."RESPUESTA_ESTUDIANTE" ADD FOREIGN KEY ("ID_PRESENTACION")
	  REFERENCES "ROOT2"."PRESENTACION_EXAMEN" ("ID_PRESENTACION") ENABLE;
  ALTER TABLE "ROOT2"."RESPUESTA_ESTUDIANTE" ADD FOREIGN KEY ("ID_PREGUNTA")
	  REFERENCES "ROOT2"."PREGUNTA" ("ID_PREGUNTA") ENABLE;
  ALTER TABLE "ROOT2"."RESPUESTA_ESTUDIANTE" ADD FOREIGN KEY ("ID_RESPUESTA")
	  REFERENCES "ROOT2"."RESPUESTA" ("ID_RESPUESTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TEMA
--------------------------------------------------------

  ALTER TABLE "ROOT2"."TEMA" ADD CONSTRAINT "FK_TEMA_UNIDAD" FOREIGN KEY ("ID_UNIDAD")
	  REFERENCES "ROOT2"."UNIDAD" ("ID_UNIDAD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UNIDAD
--------------------------------------------------------

  ALTER TABLE "ROOT2"."UNIDAD" ADD FOREIGN KEY ("ID_PLAN")
	  REFERENCES "ROOT2"."PLAN_ESTUDIO" ("ID_PLAN") ENABLE;
