/**ALTER INDEX NOMBRE_INDEX RENAME TO PK_NOMBRE;

SELECT index_name, table_name, tablespace_name
FROM user_indexes
ORDER BY table_name;

COMMIT;*/
CREATE TABLESPACE TBS_USUARIOS DATAFILE 'tbs_usuarios.dbf' SIZE 100M AUTOEXTEND ON;
CREATE TABLESPACE TBS_EXAMENES DATAFILE 'tbs_examenes.dbf' SIZE 100M AUTOEXTEND ON;
CREATE TABLESPACE TBS_PRESENTACION DATAFILE 'tbs_presentacion.dbf' SIZE 100M AUTOEXTEND ON;
CREATE TABLESPACE TBS_ESTADISTICAS DATAFILE 'tbs_estadisticas.dbf' SIZE 100M AUTOEXTEND ON;
CREATE TABLESPACE TBS_PLANESTUDIO DATAFILE 'tbs_planestudio.dbf' SIZE 50M AUTOEXTEND ON;
CREATE TABLESPACE TBS_LOB DATAFILE 'tbs_lob.dbf' SIZE 100M AUTOEXTEND ON;
CREATE TABLESPACE TBS_INDICES DATAFILE 'tbs_indices.dbf' SIZE 100M AUTOEXTEND ON;

ALTER TABLE ROOT2.USUARIO MOVE TABLESPACE TBS_USUARIOS;
ALTER TABLE ROOT2.DOCENTE MOVE TABLESPACE TBS_USUARIOS;
ALTER TABLE ROOT2.ESTUDIANTE MOVE TABLESPACE TBS_USUARIOS;
ALTER TABLE ROOT2.CURSO MOVE TABLESPACE TBS_USUARIOS;
ALTER TABLE ROOT2.GRUPO MOVE TABLESPACE TBS_USUARIOS;
ALTER TABLE ROOT2.DOCENTE_GRUPO MOVE TABLESPACE TBS_USUARIOS;
ALTER TABLE ROOT2.ESTUDIANTE_GRUPO MOVE TABLESPACE TBS_USUARIOS;

ALTER TABLE ROOT2.EXAMEN MOVE TABLESPACE TBS_EXAMENES;
ALTER TABLE ROOT2.PREGUNTA MOVE TABLESPACE TBS_EXAMENES;
ALTER TABLE ROOT2.RESPUESTA MOVE TABLESPACE TBS_EXAMENES;
ALTER TABLE ROOT2.EXAMEN_PREGUNTA MOVE TABLESPACE TBS_EXAMENES;

ALTER TABLE ROOT2.PRESENTACION_EXAMEN MOVE TABLESPACE TBS_PRESENTACION;
ALTER TABLE ROOT2.RESPUESTA_ESTUDIANTE MOVE TABLESPACE TBS_PRESENTACION;

ALTER TABLE ROOT2.ESTADISTICAS_EXAMEN MOVE TABLESPACE TBS_ESTADISTICAS;
ALTER TABLE ROOT2.ESTADISTICAS_ESTUDIANTE MOVE TABLESPACE TBS_ESTADISTICAS;
ALTER TABLE ROOT2.ESTADISTICAS_PREGUNTA MOVE TABLESPACE TBS_ESTADISTICAS;
ALTER TABLE ROOT2.ESTADISTICAS_GRUPO MOVE TABLESPACE TBS_ESTADISTICAS;
ALTER TABLE ROOT2.ESTADISTICAS_TEMA MOVE TABLESPACE TBS_ESTADISTICAS;

ALTER TABLE ROOT2.PLAN_ESTUDIO MOVE TABLESPACE TBS_PLANESTUDIO;
ALTER TABLE ROOT2.UNIDAD MOVE TABLESPACE TBS_PLANESTUDIO;
ALTER TABLE ROOT2.TEMA MOVE TABLESPACE TBS_PLANESTUDIO;
ALTER TABLE ROOT2.HORARIO MOVE TABLESPACE TBS_PLANESTUDIO;

ALTER TABLE ROOT2.PREGUNTA MOVE LOB (TEXTO) STORE AS (TABLESPACE TBS_LOB);

---------------------------------

ALTER INDEX ROOT2.PK_CURSO REBUILD TABLESPACE TBS_INDICES;

-- Índice de DOCENTE  
ALTER INDEX ROOT2.PK_DOCENTE REBUILD TABLESPACE TBS_INDICES;

-- Índice de DOCENTE_GRUPO
ALTER INDEX ROOT2.PK_DOCENTE_GRUPO REBUILD TABLESPACE TBS_INDICES;

-- Índices de ESTADISTICAS
ALTER INDEX ROOT2.PK_ESTADISTICAS_ESTUDIANTE REBUILD TABLESPACE TBS_INDICES;
ALTER INDEX ROOT2.PK_ESTADISTICAS_EXAMEN REBUILD TABLESPACE TBS_INDICES;
ALTER INDEX ROOT2.PK_ESTADISTICAS_GRUPO REBUILD TABLESPACE TBS_INDICES;
ALTER INDEX ROOT2.PK_ESTADISTICAS_PREGUNTA REBUILD TABLESPACE TBS_INDICES;
ALTER INDEX ROOT2.PK_ESTADISTICAS_TEMA REBUILD TABLESPACE TBS_INDICES;

-- Índice de ESTUDIANTE
ALTER INDEX ROOT2.PK_ESTUDIANTE REBUILD TABLESPACE TBS_INDICES;

-- Índice de EXAMEN
ALTER INDEX ROOT2.PK_EXAMEN REBUILD TABLESPACE TBS_INDICES;

-- Índice de EXAMEN_PREGUNTA
ALTER INDEX ROOT2.PK_EXAMEN_PREGUNTA REBUILD TABLESPACE TBS_INDICES;

-- Índice de GRUPO
ALTER INDEX ROOT2.PK_GRUPO REBUILD TABLESPACE TBS_INDICES;

-- Índice de HORARIO
ALTER INDEX ROOT2.PK_HORARIO REBUILD TABLESPACE TBS_INDICES;

-- Índice de PLAN_ESTUDIO
ALTER INDEX ROOT2.PK_PLAN_ESTUDIO REBUILD TABLESPACE TBS_INDICES;

-- Índice de PREGUNTA (clave primaria)
ALTER INDEX ROOT2.PK_PREGUNTA REBUILD TABLESPACE TBS_INDICES;

-- Índice de PRESENTACION_EXAMEN
ALTER INDEX ROOT2.PK_PRESENTACION_EXAMEN REBUILD TABLESPACE TBS_INDICES;

-- Índice de RESPUESTA
ALTER INDEX ROOT2.PK_RESPUESTA REBUILD TABLESPACE TBS_INDICES;

-- Índice de RESPUESTA_ESTUDIANTE
ALTER INDEX ROOT2.PK_RESPUESTA_ESTUDIANTE REBUILD TABLESPACE TBS_INDICES;

-- Índice de TEMA
ALTER INDEX ROOT2.PK_TEMA REBUILD TABLESPACE TBS_INDICES;

-- Índice de UNIDAD
ALTER INDEX ROOT2.PK_UNIDAD REBUILD TABLESPACE TBS_INDICES;

-- Índice de USUARIO
ALTER INDEX ROOT2.PK_USUARIO REBUILD TABLESPACE TBS_INDICES;

COMMIT;